build-ios/build.sh
build-release.sh
build.sh

It seems to work fine with the (intermediate) container build that I get with https://github.com/godotengine/build-containers/pull/47 (without cross-compiling toolchain).
BTW, how does the AOT toolchain intervene in the build/packaging of the templates? Or is it something that should be bundled alongside the editor builds for all desktop platforms?

Mono: Add support for iOS

---

.gitignore
build-release.sh

The sums are included both in the release folder, and in a separate
`sha512sums` folder in the base directory, to allow verifying that
the sums on the download repository haven't been tampered with.

Compute and backup SHA-512 sums for release files

---

build-linux/build.sh
build-mono-glue/build.sh
build-server/build.sh

Using the dotnet CLI can be a valid workaround, but it's not available
for 32-bit Linux.
Instead, we build the Godot API and GodotTools solutions (CIL) on Fedora
in the mono-glue container, and copy them to the Ubuntu-based Linux
containers.

Mono: Workaround segfault issue with Mono MSBuild on Ubuntu 14.04

---

build-release.sh

FYI @m4gr3d - I think it makes sense to use the `.mono` suffix here to distinguish between the two variants.
(Already used this commit for 3.2.2 RC 1 and RC 2.)

Android: Add .mono suffix for the Mono-enabled AAR

---

build-ios/build.sh
build-macosx/build.sh
build-release.sh
build.sh

Untested for now, but preparing the ground for building universal binaries with ARM64 support for macOS.
Requirements to finish this:
- 1. [x] osxcross should first get support for the ARM64 target ([upstream issue](https://github.com/tpoechtrager/osxcross/issues/227)).
- 2. [x] [Dockerfile.xcode](https://github.com/godotengine/build-containers/blob/master/Dockerfile.xcode) and [Dockerfile.osx](https://github.com/godotengine/build-containers/blob/master/Dockerfile.osx) will need to be updated to build with Xcode 12 and the latest osxcross version when it supports ARM64. (Done with https://github.com/godotengine/build-containers/pull/60.)
- 3. [ ] [Dockerfile.osx](https://github.com/godotengine/build-containers/blob/master/Dockerfile.osx) should be updated to build Mono for ARM64.
Sooo... …

OSX: Build universal binaries with ARM64

---

build-javascript/build.sh
build-release.sh

Classical builds now use Emscripten 2.0.10 and have threads and gdnative templates.
Mono builds still use Emscripten 1.39.9 for compatibility with Mono 6.12.x, so they
can only have threads support (GDNative requires 2.0.10+).

JS: Build with threads and gdnative where supported + re-enable LTO

---

build-javascript/build.sh
build.sh

Had this locally but forgot to PR.
Supersedes #15.

Mono 6.12.0.114, EMSDK values now defined in container

---

build-linux/build.sh

Also remove the definition of `use_static_cpp` as this is now done
automatically in the SCons script.
(That part actually depends on cherry-picking godotengine/godot#45629 first.)
Fixes godotengine/godot#31743.

Linux: Use GCC 4.8 for 32-bit x86

---

build-android/build.sh
build-ios/build.sh
build-javascript/build.sh
build-linux/build.sh
build-macosx/build.sh
build-mono-glue/build.sh
build-server/build.sh
build-uwp/build.sh
build-windows/build.sh

Equivalent to debug_symbols=no use_lto=yes use_static_cpp=yes.
We keep LTO disabled for iOS as users need to relink on deploy, and that's very slow
and memory hungry with LTO.

Use new production=yes option

---

build-macosx/editor_mono.entitlements
build-release.sh

Supersedes #13, thanks @sjml for the initial work and @neikeq for the buildsystem changes.
Requires https://github.com/godotengine/godot/pull/43768 to be cherry-picking in `3.2` to work.
---
Marking as draft but it's ready for review, it's just until https://github.com/godotengine/godot/pull/43768 is merged and cherry-picked and the resulting binaries are tested.

Mono/macOS: Change .app packaging and codesign editor binary

---

build-android/build.sh
build-ios/build.sh
build-javascript/build.sh
build-linux/build.sh
build-macosx/build.sh
build-mono-glue/build.sh
build-server/build.sh
build-uwp/build.sh
build-windows/build.sh
build.sh
config.sh.in

Makes it easier to distinguish between official and custom builds by allowing developers to customize `BUILD_NAME` env var.
I can make it to default to `custom_build` over `official` if you like. Of course, nothing prevents someone to use `official` name, but this will decrease the likelihood of someone compiling the editor and export templates as official, otherwise the only way to distinguish such builds is by using checksums.
Also note that `BUILD_NAME` can be fetched at run-time via script with [`Engine.get_version_info()`](https://docs.godotengine.org/en/stable/classes/class_engine.html#class-engine-method-get-version-info).

Make `BUILD_NAME` globally configurable

---

.gitignore

Note: at first I thought that it's simply not `.gitignore`d, but then I've noticed `angle` is there, but when I ran `build_release.sh`, it ended up in repository root, so makes me wonder whether it's a bug. I've prematurely made the PR instead of creating an issue about this so feel free to close this PR and fix the underlying issue, but I think merging this won't hurt anything anyways.
Here's the code:
https://github.com/godotengine/godot-build-scripts/blob/f3a5097159933becc1df63f0b6c567c2ff4830fa/build-release.sh#L263-L267

Add `angle.7z` to `.gitignore`

---

build-macosx/editor.entitlements

To allow loading GDNative plug-ins, without requiring code signing.
Otherwise, loading will fail unless the library is signed by the same team ID as the app.
With this entitlement it will allow loading, all Gatekeeper restrictions still applies to the unsigned plugins.
Fixes: https://github.com/godotengine/godot-git-plugin/issues/58

Add `Disable Library Validation` entitlement.

---

build-release.sh

It's time we start distributing the web editor as self-hostable
application if so desired.

[HTML5] Produce the editor zip in release folder.

---

build-ios/build.sh
build-macosx/build.sh
build.sh

Follow-up to https://github.com/godotengine/build-containers/pull/77.
OSX/iOS: Now using Xcode 12.4 and newer osxcross
`NO_LDID` no longer needed as osxcross is no longer fake-signing with LDID.

Use images version 3.x-mono-6.12.0.122

---

build-release.sh

This should fix potentially improper signing done by osxcross,
and allow running those on Apple M1.
---
Draft for now as I haven't actually tested this code. I also wonder if the `data_*` stuff in the Mono templates also needs to be signed with the same command or if it will be sufficient as is.

OSX: Dummy sign templates with linker-signed

---

build-ios/build.sh
build-release.sh

Add ARM64 iOS simulator builds, and `.xcframework` creation.
Depends on https://github.com/godotengine/godot-mono-builds/pull/30 and https://github.com/godotengine/build-containers/pull/68

Add Apple Silicon iOS simulator build support. Build main lib and mono libs as `.xcframework`s.

---

build-ios/build.sh

Cf. https://github.com/godotengine/build-containers/pull/85

iOS: Disable non-working arm64 simulator builds

---

build-ios/build.sh

iOS: Further changes to disable non-working arm64 simulator builds

---

build-linux/build.sh
build-macosx/build.sh
build-mono-glue/build.sh
build-release.sh
build-server/build.sh
build-windows/build.sh
build.sh

Cf. godotengine/build-containers#84
- Linux builds are now done on Fedora using a custom Godot SDK instead of
relying on an old Ubuntu version for portability.
Removes need for various workarounds.
- macOS Mono builds now include support for Apple Silicon / arm64, both
architectures are concatenated in universal binaries.
This new config is compatible with the `3.x` branch for Godot 3.4.
It might or might not work as is for `master` / Godot 4.0. Porting it will
be the next step.
---
Also includes #41, will rebase once merged.

Update scripts for overhauled build containers (`3.x-mono-6.12.0.147`)

---

build-release.sh

Same as done for non-Mono builds already.
- Follow up to #49.
- Fixes https://github.com/godotengine/godot/issues/61672.

Windows: Add .cmd script to run Mono editor with console

---

build-macos/build.sh
build-release.sh

Should be merged alongside https://github.com/godotengine/godot/pull/63096. Like #50, I haven't tested this.
Name changes:
```
linux_x11_64_release   -> linux_release.x86_64
linux_x11_64_debug     -> linux_debug.x86_64
linux_x11_32_release   -> linux_release.x86_32
linux_x11_32_debug     -> linux_debug.x86_32
windows_64_release.exe -> windows_release_x86_64.exe
windows_64_debug.exe   -> windows_debug_x86_64.exe
windows_32_release.exe -> windows_release_x86_32.exe
windows_32_debug.exe   -> windows_debug_x86_32.exe
godot_macos_release.64 -> godot_macos_release.universal
godot_macos_debug.64   -> godot_macos_debug.universal
```
For Linux, remove `_x11`, and put the architecture at the end with a dot so it matches the pattern used for exported games. For Windows, originally I was going to …

CPU architecture name changes for Windows, Mac, and Linux templates

---

build-linux/build.sh
build-release.sh
build-windows/build.sh

This PR explicitly sets the `arch=` flag for Windows and Linux build commands. In the current master, explicitly setting `env["arch"]` to x86 basically only changes the file name suffix. This PR should make the build scripts forwards compatible with https://github.com/godotengine/godot/pull/55778 yet still work with the current master of Godot.
Note: I haven't tested this PR. Most of it is replacing `.64` with `.x86_64` etc so it probably works.

CPU architecture name changes for Windows/Linux outputs from SCons

---

build-javascript/build.sh
build-release.sh
build.sh

I made a test build with these changes yesterday: https://downloads.tuxfamily.org/godotengine/testing/4.0.alpha15-ish.web/
I couldn't get the web editor build to render anything in Firefox or Chromium on Linux, not sure why.
It might be my CORS server deployment methods which isn't working as expected. Or maybe we regressed on WebGL 2.0 support again.

JavaScript: Re-enable build for 4.0 now that WebGL 2 works

---

build-android/build.sh
build-ios/build.sh
build-linux/build.sh
build-mono-glue/build.sh
build-web/build.sh
build-windows/build.sh
build.sh

~Draft for now, only ported Linux and Windows for testing,~ and the Linux builds are failing to link `libnethost.a` (and I suspect the Windows builds would fail like https://github.com/godotengine/godot/issues/64950).
*Edit:* Not working yet but cleans up a lot of the Mono stuff we won't need anymore. But at least all platform code is updated so I can do further refactoring without having the Mono things in the way.
Uses containers from https://github.com/godotengine/build-containers/pull/113.

.NET 6: Initial port of build scripts for 4.0

---

build-release.sh
build-web/build.sh
build.sh

Follow-up to https://github.com/godotengine/godot/pull/65094.
Also reverts LTO change from #62, we found that while it's much slower to link, full LTO still produces smaller binaries and that's quite important for the Web platform.

Web: Handle new template names and `dlink_enabled=yes`

---

build-web/build.sh

Fabio found that full LTO produces smaller binaries than ThinLTO,
and that's quite important for the Web platform:
```
18M	sizes/full_lto_no_txt.wasm
3,5M	sizes/full_lto_no_txt.wasm.br
20M	sizes/full_lto.wasm
4,1M	sizes/full_lto.wasm.br
20M	sizes/thin_lto_no_txt.wasm
3,8M	sizes/thin_lto_no_txt.wasm.br
23M	sizes/thin_lto.wasm
4,5M	sizes/thin_lto.wasm.br
```
But for an obscure reason LLVM's full LTO cannot linking with multiple
threads, and so it's slow as heck (10-15 min per build).
So we work it around by starting all builds in parallel so that they
can all link at the same time.
The code to do so is pretty ugly, could be refactored further.

Web: Refactor build script to run in parallel with full LTO

---

build-android/build.sh

Needed after https://github.com/godotengine/godot/pull/55778.
Not sure how alpha15 built properly without this :O
I suspect it actually built only `arm64` templates (the default) and we didn't notice because gradle can handle this without issue.
That would explain this size difference:
```
Godot_v4.0-alpha14_android_editor.apk | 2022-Aug-11 10:22:34 | 184.5M
Godot_v4.0-alpha14_export_templates.tpz | 2022-Aug-11 10:28:58 | 683.9M
```
```
Godot_v4.0-alpha15_android_editor.apk | 2022-Aug-30 12:13:41 | 47.6M
Godot_v4.0-alpha15_export_templates.tpz | 2022-Aug-30 12:18:04 | 469.4M
```

Android: Fix still using android_arch over arch

---

build-android/build.sh
build-ios/build.sh
build-macos/build.sh
build-mono-glue/build.sh
build-release.sh
build-web/build.sh

Does not attempt to build Android, iOS and Web since it's not supported currently.
Follow-up to #64.
Tested successfully with the desktop editor 64-bit builds so far: https://downloads.tuxfamily.org/godotengine/testing/4.0-alpha16-mono-editor/mono/
I'll now do a full build of all desktop editor and template builds to fully validate this PR and be ready for 4.0 beta 1.

.NET 6: Further update build scripts for 4.0, works for desktop releases

---

build-android/build.sh
build-ios/build.sh
build-linux/build.sh
build-macos/build.sh
build-mono-glue/build.sh
build-release.sh
build-web/build.sh
build-windows/build.sh

Follow up to https://github.com/godotengine/godot/pull/66242
Tested successfully on 4.0-beta3 build.

Unify `target`/`tools` arguments after upstream change

---

build-ios/build.sh
build-macos/build.sh

Depends on https://github.com/godotengine/build-containers/pull/116

Xcode: Update macOS and iOS scripts for to Xcode 14.1 (macOS 13.0, iOS 16.1)

---

.gitignore
build-android/build.sh
build-android/upload-mavencentral.sh
build-release.sh
build.sh
config.sh.in

- Address step 3 in https://github.com/godotengine/godot-proposals/issues/4230
- Add environment variables to sign the Godot Android Editor release build
**Note:** Should be merged alongside https://github.com/godotengine/godot/pull/74569
[3.x version](https://github.com/godotengine/godot-build-scripts/pull/79)

Add logic to upload the Godot Android library to MavenCentral

---

.gitignore
build-android/build.sh
build-android/upload-mavencentral.sh
build-release.sh
build.sh
config.sh.in

- Address step 3 in https://github.com/godotengine/godot-proposals/issues/4230
- Add environment variables to sign the Godot Android Editor release build
**Note:** Should be merged alongside https://github.com/godotengine/godot/pull/74583
[main version](https://github.com/godotengine/godot-build-scripts/pull/78)

[3.x] Add logic to upload the Godot Android library to MavenCentral

---

build-android/build.sh
build-release.sh

4.2+ only as it depends on https://github.com/godotengine/godot/pull/73257.
That means I'll branch off the previous commit 21af2c7666528dd020c3ce18a3e1043ca1fc56e9 as `4.1` (and `4.0`) and keep using the matching container (Fedora 36 based) for 4.0.x and 4.1.x releases.

.NET: Add support for Android builds

---

build-macos/build.sh
build-windows/build.sh
build.sh

Download static ANGLE libs to link them in Windows and macOS builds

---

build-release.sh

Fixes #80.
Still needs actual testing, I haven't run the build script yet.
Should be cherry-picked to `3.5`.

UWP: Update version of ANGLE DLLs

---

build-ios/build.sh
build-release.sh

Draft as it depends on https://github.com/godotengine/godot/pull/82729 being merged.
Tested successfully with this build: https://downloads.tuxfamily.org/godotengine/testing/4.2-dev6+pr82729/mono/

.NET: Add support for iOS builds

---

build-release.sh
clean-release.sh
clean.sh

This is a requirement for all current versions of Godot, both stable and pre-releases. I unified this new option with the old one to publish nuget packages, as it all seems related. (Old `-n` options is kept for compatibility.)
I haven't tested this, not really sure how, but I think it should be pretty straight-forward.

Publish Android library from the main build-release script

---

build-android/build.sh
build-android/upload-mavencentral.sh
build-web/build.sh

Temporary change until we switch to newer build containers with it.
Also temporarily disable closure compiler for Web editor, needed for 4.2 beta 1 and beta 2, should be fixed upstream afterwarads.

Android: Install JDK 17 needed for 4.2-beta2 and later

---

build-linux/build.sh

Needs further investigation and reporting the bug upstream.
Technically I've only tested it to be an issue on ARM64 on a Raspberry Pi 5, but I'm disabling it for ARM32 too to be safe.
@hiulit reported that Ubuntu 23.10 seemed to work fine with our LTO'd binaries, so looking at the differences between RPiOS and Ubuntu 23.10 might help pinpoint what causes the issue.
Might be GCC or glibc bug?

Linux: Disable LTO for ARM64/ARM32, it crashes on Raspberry Pi OS

---

build-ios/build.sh
build-linux/build.sh
build-macosx/build.sh
build-mono-glue/build.sh
build-release.sh

Backport of #89 and #90, in sync with https://github.com/godotengine/build-containers/pull/135.
In the 3.x branch, the situation with `arch` and `bits` is very brittle, so we only add the explicit `arch` argument for the arm32/arm64 builds. x86_32 still relies on `bits=32`.
This would all be worth refactoring upstream like we did for 4.0, but it's a major undertaking and breaking change, which I'd prefer to avoid in 3.6.
For Linux builds, we move the `strip` calls to the link stage, as this
needs to be done with the arch-appropriate `strip` binary, so it's easier
done there. In `master`, we now let the compiler strip automatically
during the build if no debug symbols are requested, but this change
wasn't backported to 3.x.
---
Tested successfully for almost all platforms, I'm just …

[3.x] Update all to new toolchains, add Linux arm64 and arm32 builds

---

build-windows/build.sh
build.sh

Partially fixes https://github.com/godotengine/godot/issues/86490
It won't download and package proprietary `dxil.dll` with the editor/templates, but it's loaded dynamically so it won't prevent the editor to work with other renderers and can be added without building the engine. Also, might work if Windows is in developer mode, since library is used only for shader signing.

[Windows] Enable D3D12 support.

---

build-ios/build.sh
build-macos/build.sh

Following merge of https://github.com/godotengine/build-containers/pull/141.
Used successfully for 4.3-beta2.

macOS/iOS: Update SDK versions to Xcode 15.4

---

build-macos/build.sh
build-release.sh

Already removed for Linux in #90.

Don't strip Windows and macOS binaries, already done at build time

---

build-release.sh
build-windows/build.sh
build.sh

Depends on https://github.com/godotengine/build-containers/pull/144
Depends on https://github.com/godotengine/godot/pull/94533

Add commands to make ARM64 Windows engine builds, update Mesa/NIR and ANGLE downloads to the latest releases.

---

build-windows/build.sh
build.sh

Follow-up to https://github.com/godotengine/godot/pull/79126 to finally make it active on Steam builds.
The other option would be to enable this option for the generic Windows builds, but we haven't tested this much during beta/RC and I'm not too keen on having the binary always probe for steamapi for the majority of users who don't use Godot through Steam.

Windows: Add extra editor build with `steamapi=yes` for stable releases

---

build-android/build.sh
build-release.sh

Requires https://github.com/godotengine/godot/pull/96624

Add support for Android editor builds for Meta devices

---

build-android/build.sh

Build the Android templates for .NET using the 'mono' edition that contains additional dependencies required by .NET projects to support Android OS APIs (like crypto).
- Follow-up to https://github.com/godotengine/godot/pull/88803.

.NET: Build Android templates with 'mono' edition

---

build-ios/build.sh
build-macos/build.sh

Depends on https://github.com/godotengine/build-containers/pull/150.

Update toolchains based on Fedora 41 for Godot 4.4

---

.gitignore
build-release.sh
clean-release.sh
clean.sh

I've used this for 4.4-stable to prepare signed Windows binaries for Steam.
This is only relevant for stable releases.

build-release: Copy and sign Steam Windows exe for stable releases

---

build-release.sh
build.sh
config.sh.in
publish-release.sh

This is hacked together but seems to work, tested with 4.4.1-stable.
More work would be good eventually to rely less on some adhoc configuration of Steam/EGS/godot-builds paths on our build server. We should move those configs to a Git repository (this one, or a separate one, possibly private as only us should use it), but this should be done carefully as there are some passwords involved (which should be moved to `config.sh`).
For now, this should be a good start though to automate some of the process.
Worth noting, for a stable release, `./publish-release.sh -l` can be used to mark the release as latest - this should only be used for the most recent supported release (e.g. 4.4.1 now, but a future 4.3.1 shouldn't be marked as stable). This controls which version of the Web editor is the …

publish-release: Add support to upload stable builds to GH, Steam, EGS and itch.io

---

build-android/build.sh
build-android/upload-mavencentral.sh

Build scripts counterpart to https://github.com/godotengine/godot/pull/104819; this PR updates the build scripts so that the content generated for the `editor` build are preserved when copying out the `godot` directory.
The `mavencentral` publish command has been updated to publish all publications in the project.

Update the Android build scripts to allow exporting 'Godot Tools' Android library to MavenCentral

---

build-android/build.sh

Build scripts counterpart to https://github.com/godotengine/godot/pull/105605.
This PR updates the Android build process to generate native debug symbols. This is done by setting `debug_symbols=yes` for the `scons` build, and letting `gradle` strips out the generated `so` artifacts. As part of the stripping process, `gradle` will generate a separate debug symbols.

Setup Android debug symbols

---

build-windows/build.sh
build.sh

Depends on https://github.com/godotengine/godot/pull/106659
32-bit builds crash was fixed (https://github.com/AccessKit/accesskit-c/issues/36)

Update access-kit to 0.16.0, reenable it for 32-bit Windows builds.

---

build-ios/build.sh
build-release.sh
build-visionos/build.sh
build.sh

Depends:
- https://github.com/godotengine/build-containers/pull/154
Adds support for building visionOS and tvOS templates

Apple: add visionOS build support; unify build container

---

build-release.sh

This should address the issue with uploading the Android native debug symbols.
Fixes https://github.com/godotengine/godot-build-scripts/issues/125

Update the name of the Android native debug symbols files to start with a `g`
